Import('env')

env.InstallHTML(['monomer.pdb', 'hliq.dat'])

env.InstallHTML(['css/foxsdock.css'], 'css')

env.InstallHTML(['img/logo.png', 'img/logo2.gif', 'img/logo3.png',
                 'img/foxsdock_flow.jpg'], 'img')
